name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9-slim-buster
    timeout-minutes: 5
    env:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
      - name: update dependencies
        run: apt-get update && apt-get -yq install build-essential libssl-dev swig
      - uses: actions/checkout@v2
      - name: Cache pip and pipenv
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            ~/.cache/pip3
            ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip3-
            ${{ runner.os }}-pipenv-
      # Install pipenv
      - name: Install pip3
        run: pip3 install pipenv
      # Create and activate environment
      - name: Create environment
        working-directory: ./src/
        run: pipenv install
      # run tests
      - name: Run tests
        run: |
          coverage run -m pytest src/tests
          coverage report
          mkdir ./coverage
          coverage xml -d ./coverage/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage1.xml,./coverage2.xml
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true